/**
 * Regenerates tests/fixtures/golden-hashes.json.
 *
 * Run this only when a simulation change is *intended* to alter world outcomes:
 *
 *   npm run golden:update
 *
 * The committed fixture exists so that an unintended behavioral change fails a
 * test instead of silently passing. Determinism tests that only compare a build
 * against itself cannot detect that class of regression.
 *
 * The fixture is generated with node --experimental-strip-types and no third
 * party dependencies, matching the rest of the repository.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { runTick, runTicks } from "../src/sim/engine.ts";
import { WorldStore } from "../src/sim/persistence.ts";
import { createPrototypeWorld } from "../src/sim/scenario.ts";
import { stateHash } from "../src/sim/state.ts";

/** Seeds exercised by the documented milestone gate in scripts/evaluate-milestone.sh. */
export const GOLDEN_SEEDS = [1847, 2718, 4096];
/** The gate runs 72 ticks, which is twelve in-world days. */
export const GOLDEN_TICKS = 72;
/** Recovery is proven on one seed, split at 47 ticks so the split lands off a snapshot boundary. */
export const RECOVERY_SEED = 1847;
export const RECOVERY_SPLIT_TICKS = 47;

export interface GoldenSeedRecord {
  seed: number;
  stateHash: string;
  eventCount: number;
}

export interface GoldenRecoveryRecord {
  seed: number;
  splitAtTick: number;
  continuousStateHash: string;
  splitStateHash: string;
  replayedEvents: number;
}

export interface GoldenHashes {
  note: string;
  ticks: number;
  generatedWith: { node: string; icu: string };
  seeds: GoldenSeedRecord[];
  recovery: GoldenRecoveryRecord;
}

export function buildGoldenHashes(): GoldenHashes {
  const seeds: GoldenSeedRecord[] = GOLDEN_SEEDS.map((seed) => {
    const result = runTicks(createPrototypeWorld(seed), GOLDEN_TICKS);
    return {
      seed,
      stateHash: stateHash(result.state),
      eventCount: result.events.length,
    };
  });

  const continuous = runTicks(createPrototypeWorld(RECOVERY_SEED), GOLDEN_TICKS);
  const continuousStateHash = stateHash(continuous.state);

  const directory = mkdtempSync(join(tmpdir(), "open-era-golden-"));
  const databasePath = join(directory, "recovery.sqlite");
  let splitStateHash: string;
  let replayedEvents: number;
  try {
    const store = new WorldStore(databasePath);
    const world = createPrototypeWorld(RECOVERY_SEED);
    store.initialize(world);
    for (let index = 0; index < RECOVERY_SPLIT_TICKS; index += 1) {
      const result = runTick(world);
      store.appendTick(result.events, world);
    }
    store.close();

    const reopened = new WorldStore(databasePath);
    const recovered = reopened.recover();
    replayedEvents = recovered.replayedEvents;
    for (let index = RECOVERY_SPLIT_TICKS; index < GOLDEN_TICKS; index += 1) {
      const result = runTick(recovered.state);
      reopened.appendTick(result.events, recovered.state);
    }
    splitStateHash = stateHash(recovered.state);
    reopened.close();
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }

  if (splitStateHash !== continuousStateHash) {
    throw new Error(
      `Recovery diverged for seed ${RECOVERY_SEED}: ${splitStateHash} !== ${continuousStateHash}`,
    );
  }

  return {
    note: "Generated by scripts/update-golden-hashes.ts. Regenerate with: npm run golden:update",
    ticks: GOLDEN_TICKS,
    generatedWith: { node: process.version, icu: process.versions.icu ?? "unknown" },
    seeds,
    recovery: {
      seed: RECOVERY_SEED,
      splitAtTick: RECOVERY_SPLIT_TICKS,
      continuousStateHash,
      splitStateHash,
      replayedEvents,
    },
  };
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const outputPath = resolve(here, "../tests/fixtures/golden-hashes.json");
  const golden = buildGoldenHashes();
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${JSON.stringify(golden, null, 2)}\n`, "utf8");

  for (const record of golden.seeds) {
    console.log(`seed ${record.seed}: ${record.stateHash} (${record.eventCount} events)`);
  }
  console.log(
    `recovery seed ${golden.recovery.seed}: split at ${golden.recovery.splitAtTick} ticks matched continuous run`,
  );
  console.log(`Wrote ${outputPath}`);
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : "";
if (invokedPath === resolve(fileURLToPath(import.meta.url))) main();
